import pickle

import numpy as np
import glob
from argparse import ArgumentParser
from itertools import chain
from tqdm import tqdm

from .retriever import BaseFaissIPRetriever

import logging
logger = logging.getLogger(__name__)
logging.basicConfig(
    format="%(asctime)s - %(levelname)s - %(name)s -   %(message)s",
    datefmt="%m/%d/%Y %H:%M:%S",
    level=logging.INFO,
)


def search_queries(retriever, q_reps, p_lookup, args):
    # Use batched search for large query sets to avoid submitting all query
    # vectors to FAISS at once.
    if args.batch_size > 0:
        # batch_search splits the query matrix and calls search repeatedly.
        all_scores, all_indices = retriever.batch_search(q_reps, args.depth, args.batch_size, args.quiet)
    else:
        # Search all queries in a single FAISS call when the query set is small.
        all_scores, all_indices = retriever.search(q_reps, args.depth)

    # FAISS returns row offsets in the internal index. Map those offsets back to
    # original passage ids with the lookup table saved during encoding.
    psg_indices = [[int(p_lookup[x]) for x in q_dd] for q_dd in all_indices]
    psg_indices = np.array(psg_indices)
    # Return score and passage-id matrices with shape (num_queries, depth).
    return all_scores, psg_indices


def write_ranking(corpus_indices, corpus_scores, q_lookup, ranking_save_file):
    # Write a plain ranking file with one `qid docid score` tuple per line.
    # corpus_indices has shape (num_queries, depth) and stores passage ids.
    # corpus_scores: shape (num_queries, depth)
    with open(ranking_save_file, 'w') as f:
        for qid, q_doc_scores, q_doc_indices in zip(q_lookup, corpus_scores, corpus_indices):
            # Keep the output sorted by descending retrieval score for each query.
            score_list = [(s, idx) for s, idx in zip(q_doc_scores, q_doc_indices)]
            score_list = sorted(score_list, key=lambda x: x[0], reverse=True)
            for s, idx in score_list:
                f.write(f'{qid}\t{idx}\t{s}\n')


def pickle_load(path):
    # Load encoded vectors and their id lookup table. Encoding writes
    # pickle.dump((reps, lookup)), where lookup aligns one-to-one with reps.
    with open(path, 'rb') as f:
        reps, lookup = pickle.load(f)
    # FAISS indexes expect float32 input for standard CPU/GPU search.
    return np.array(reps).astype('float32'), lookup


def pickle_save(obj, path):
    # Persist search results or intermediate vector data for downstream merging.
    with open(path, 'wb') as f:
        pickle.dump(obj, f)


def main():
    parser = ArgumentParser()
    parser.add_argument('--query_reps', required=True)
    parser.add_argument('--passage_reps', required=True)
    parser.add_argument('--batch_size', type=int, default=128)
    parser.add_argument('--depth', type=int, default=1000)
    parser.add_argument('--save_ranking_to', required=True)
    parser.add_argument('--save_text', action='store_true')
    parser.add_argument('--quiet', action='store_true')
    parser.add_argument('--use_gpu', action='store_true')
    parser.add_argument('--gpu_shard', action='store_true',
                        help='Shard the index across GPUs instead of replicating it on each device.')
    parser.add_argument('--gpu_fp16', action='store_true',
                        help='Store vectors in float16 on GPU to save memory.')
    parser.add_argument('--faiss_omp_num_threads', type=int, default=64,
                        help='Number of OpenMP threads FAISS can use.')

    args = parser.parse_args()

    index_files = glob.glob(args.passage_reps)
    logger.info(f'Pattern match found {len(index_files)} files; loading them into index.')

    p_reps_0, p_lookup_0 = pickle_load(index_files[0])
    retriever = BaseFaissIPRetriever(
        p_reps_0.shape[1],
        use_gpu=args.use_gpu,
        gpu_shard=args.gpu_shard,
        gpu_fp16=args.gpu_fp16,
        faiss_omp_num_threads=args.faiss_omp_num_threads,
    )
    # Load all passage shards into one FAISS index. The first shard provides the
    # vector dimension needed to construct the retriever; every shard then adds
    # its vectors and appends its lookup ids to the global lookup list.
    shards = chain([(p_reps_0, p_lookup_0)], map(pickle_load, index_files[1:]))
    if len(index_files) > 1:
        # Show progress when the corpus is split across multiple files.
        shards = tqdm(shards, desc='Loading shards into index', total=len(index_files))
    look_up = []
    for p_reps, p_lookup in shards:
        # FAISS stores vectors in insertion order; keep lookup in the same order.
        retriever.add(p_reps)
        look_up += p_lookup

    # Load query vectors and query ids generated by tevatron.driver.encode.
    q_reps, q_lookup = pickle_load(args.query_reps)
    q_reps = q_reps

    # Search the index and convert internal FAISS offsets to passage ids.
    logger.info('Index Search Start')
    all_scores, psg_indices = search_queries(retriever, q_reps, look_up, args)
    logger.info('Index Search Finished')

    # Save either a human-readable ranking or a pickle shard for later reduction.
    if args.save_text:
        write_ranking(psg_indices, all_scores, q_lookup, args.save_ranking_to)
    else:
        pickle_save((all_scores, psg_indices), args.save_ranking_to)


if __name__ == '__main__':
    main()
